#!/usr/bin/env bash
# Quick Reference for Ansible Essentials Playbook

## Directory Structure
echo "=== Project Structure ==="
echo "roles/              - 9 essential roles (apt, packages, users, ssh, timezone, hostname, firewall, mail, updates)"
echo "playbooks/          - 5 execution playbooks (site, security, updates, system, diagnostic)"
echo "inventory/          - Host definitions and inventory examples"
echo "group_vars/         - Group-level variables"
echo "host_vars/          - Host-specific variables"
echo "templates/          - Jinja2 templates directory"
echo "library/            - Custom Ansible modules"
echo "filter_plugins/     - Custom filters"
echo ""

## Quick Commands
echo "=== Essential Commands ==="
echo ""
echo "1. View your hosts:"
echo "   cat inventory/hosts"
echo ""
echo "2. Edit host inventory:"
echo "   vim inventory/hosts"
echo ""
echo "3. View role defaults:"
echo "   cat roles/ssh/defaults/main.yml"
echo ""
echo "4. Create group variables:"
echo "   mkdir -p group_vars"
echo "   vim group_vars/all.yml"
echo ""
echo "5. Dry-run (check mode):"
echo "   ansible-playbook playbooks/site.yml --check"
echo ""
echo "6. Run complete configuration:"
echo "   ansible-playbook playbooks/site.yml"
echo ""
echo "7. Run specific role only:"
echo "   ansible-playbook playbooks/site.yml --tags=ssh"
echo ""
echo "8. Run with verbose output:"
echo "   ansible-playbook playbooks/site.yml -vv"
echo ""
echo "9. Skip specific role:"
echo "   ansible-playbook playbooks/site.yml --skip-tags=mail"
echo ""
echo "10. Syntax check:"
echo "    ansible-playbook playbooks/site.yml --syntax-check"
echo ""

## Available Playbooks
echo "=== Available Playbooks ==="
echo "site.yml       - Complete system configuration (all roles)"
echo "security.yml   - SSH and firewall hardening"
echo "updates.yml    - APT and package updates"
echo "system.yml     - Hostname and timezone"
echo "diagnostic.yml - System validation"
echo ""

## Available Tags
echo "=== Available Tags ==="
echo "apt           - APT repository management"
echo "packages      - Package installation"
echo "users         - User account management"
echo "ssh           - SSH configuration"
echo "timezone      - Timezone and NTP"
echo "hostname      - Hostname configuration"
echo "firewall      - UFW firewall"
echo "mail          - Postfix mail service"
echo "updates       - Automatic updates"
echo ""

## Common Configuration Options
echo "=== Common Configuration Variables ==="
echo ""
echo "System Timezone:"
echo "  system_timezone: UTC"
echo ""
echo "SSH Hardening:"
echo "  ssh_permit_root_login: 'no'"
echo "  ssh_password_auth: 'no'"
echo "  ssh_hardened_ciphers: true"
echo ""
echo "Firewall Rules:"
echo "  firewall_rules:"
echo "    - rule: allow"
echo "      port: 80"
echo "      proto: tcp"
echo ""
echo "Users:"
echo "  user_accounts:"
echo "    - username: ansible"
echo "      shell: /bin/bash"
echo "      groups: [sudo]"
echo ""
echo "Mail Relay:"
echo "  postfix_relayhost: smtp.gmail.com"
echo "  postfix_relayport: 587"
echo ""

## Troubleshooting
echo "=== Troubleshooting ==="
echo ""
echo "Test SSH connectivity:"
echo "  ansible all -m ping -i inventory/hosts"
echo ""
echo "Check Python availability:"
echo "  ansible all -m setup -i inventory/hosts"
echo ""
echo "List all variables:"
echo "  ansible all -m debug -a 'var=hostvars[inventory_hostname]' -i inventory/hosts"
echo ""
echo "Get role defaults:"
echo "  cat roles/ROLE_NAME/defaults/main.yml"
echo ""
echo "Check host variables:"
echo "  cat host_vars/HOSTNAME.yml"
echo ""

## Documentation
echo "=== Documentation Files ==="
echo "README.md              - Quick reference"
echo "README_FULL.md         - Complete documentation"
echo "IMPLEMENTATION_SUMMARY.md - Project details"
echo ""

echo "Happy Ansible automation! 🚀"
